# Site settings
title: "Leaks My Id"
description: "Never trust security and privacy in the internet world."
baseurl: "/"
url: "https://leaks.my.id"
author: "Mr.X"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
